all:
	make -C PruebaSwamp
	make -C SaludoAlHumedal
	make -C BatallaPorNordelta
	make -C KernelDeadlock
	make -C KernelPlanificacion
	make -C KernelSuspension
	make -C MemoriaAsignacion
	make -C MemoriaReemplazoMMU
	make -C MemoriaTLB/FIFO
	make -C MemoriaTLB/LRU
